### ISSUE TITLE
Migrate asynctest to stdlib's AsyncMock

### ISSUE THREAD

**Issue by fabaff** [rajlaud/pysqueezebox#3]
Asynctest doesn't work with Python 3.8 and above.

Asynctest upstream is aware of this breakage and recommends using the built-in AsyncMock instead.

See also Martiusweb/asynctest#144 and Martiusweb/asynctest#126

**Comment by rajlaud** [comment]
Thanks. AsyncMock works fine for my tests, so I made this change. See https://github.com/rajlaud/pysqueezebox/commit/a8e3cf929783ea9798f7f4d8344505b73b4b0b6c
