### ISSUE TITLE
Support for Squeezebox alarms?

### ISSUE THREAD

**Issue by wollew** [rajlaud/pysqueezebox#6]
Moving from FHEM to Home Assistant I found that HA's support for Squeezeboxes is incomplete when it comes to their alarm clock functionality. Maybe one could try to work around it using call_query on the LMS server entity, but having the alarm clock data in the player's attributes (or something similar, I am not fully sure of what the proper HA way to do it would be) seems more convenient. So the question is, if I, in a first step, come up with a PR for this library, would you be willing to have a look at it? If yes, I'd try, if not, fair enough, then I'd probably go the pyscript way for my own HA instance or something similar.

**Comment by rajlaud** [comment]
Yes, I'd be happy to take a look at a PR to this library to support alarms. I don't use alarms myself, but I'm all for trying to properly integrate them into HA.
