### ISSUE TITLE
0.9.x break favorites functionality

### ISSUE THREAD

**Issue by peteS-UK** [rajlaud/pysqueezebox#9]
Hi @rajlaud .  The 0.9.x versions of the lib break the favorites functionality that was working in 0.8.1.  I just get

```
2024-09-25 07:49:42.041 DEBUG (MainThread) [homeassistant.components.squeezebox.media_player] Reached async_browse_media with content_type None and content_id None
2024-09-25 07:49:42.042 DEBUG (MainThread) [pysqueezebox.server] URL: http://192.168.3.20:9000/jsonrpc.js Data: {"id": "1", "method": "slim.request", "params": ["", ["favorites", "0", "1"]]}
2024-09-25 07:49:42.059 ERROR (MainThread) [pysqueezebox.server] Failed communicating with LMS(http://192.168.3.20:9000/jsonrpc.js): <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
```

when I try and list favorites with 0.9.1 or 0.9.2.  I'll try and dig later, but wanted to let you know asap.  If I just change the manifest from the dev branch back to 0.8.1 (and remove the model stuff from media_player), then it works again, so it looks like something got lost in the version changes.

**Comment by peteS-UK** [comment]
I haven't had a chance to look at the lib yet, but shouldn't the query be ["favorites", "items","0", "1"]], not just  ["favorites","0", "1"]], although that would only list 1 favorite anyway so I may be misinterpreting.

**Comment by peteS-UK** [comment]
Hmm - confused.  I can't see any of your favorites functionality in server.py now.

**Comment by peteS-UK** [comment]
Ok - very strange.  If I look at the diff between 0.7.1 and 0.8.1, none of the favorites stuff is in there.  Also, if I look at the 0.8.1 library which gets downloaded when I set the manifest, it has all of the favs stuff - i.e. the library does have it, but the source code in the 0.8.1 release has lost it all.  I guess one of the other 0.8.1 commits must have overwritten your commit on favs.  I also can't see a PR to pull your favorites-support branch into master, so I guess that PR got reversed at some point.

**Comment by rajlaud** [comment]
Oops, that was not intentional. I'll fix and cut a new release.

**Comment by peteS-UK** [comment]
I've tried to re-merge your branch contents, but the difference between them looks too complex.  It looks like just server.py.  Just trying to copy to the relevant changes across to a 0.9.2 base.

**Comment by peteS-UK** [comment]
Hmm - that was messy.  Give this a try ....
[server.zip](https://github.com/user-attachments/files/17135776/server.zip)
Haven't done that much testing, but it seems to work.

**Comment by rajlaud** [comment]
Thanks Pete - I'm going to reconcile manually just to make sure I
understand what happened here. Hoping to get the fix out today.

**Comment by peteS-UK** [comment]
> Thanks Pete - I'm going to reconcile manually just to make sure I understand what happened here. Hoping to get the fix out today.

Yes, I think that's the only way - there's a lot of changes since 0.7.1 which was the base for the favs version.  I just ended up manually copying the new areas over from the favs branch, but there were also some other changes required in async_query_category as it'd been restructured.

**Comment by peteS-UK** [comment]
BTW - I noticed one other thing when I was doing some testing - playing a playlist works fine, but playing an item from a playlist doesn't do anything.  Not a big deal as I think it's been like that anyway, but just noticed it.

**Comment by rajlaud** [comment]
Fixed the favorites support issue. It looks like when we added favorites I published from the favorites-support branch, so that never got merged in.

Now merged in so we won't have this problem with future release.

**Comment by peteS-UK** [comment]
Thanks @rajlaud .  All looks good with 0.9.3 and good to see frenck has merged the PR already, so all should be good with 2024.10 :-)

**Comment by peteS-UK** [comment]
Hi @rajlaud.  Not sure if you meant to, but just FYI, I was looking a the diff between 0.9.2 and 0.9.3 https://github.com/rajlaud/pysqueezebox/commit/e08adb3e9356a2dff3b80d0c19962ce7888a1993 when you merged the favs branch, it looks like you lost some other changes you'd made in the mean time (some asserts etc.). and e.g.

![image](https://github.com/user-attachments/assets/ad816a58-e8c3-4c59-a8b7-f7dd317a3ff1)

**Comment by rajlaud** [comment]
Yeah, I ended up changing some of the typing code too as I brought everything together. Definitely don't want to go down that diverging branch road again!
